name: qqwry DAT File Generator

on:
  schedule:
    # 每天9点和21点执行
    - cron: '0 9,21 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          npm install pinyin

      - name: Download PureIP Database
        run: |
          # 从jsDelivr下载纯真IP数据库
          curl -L "https://cdn.jsdelivr.net/npm/qqwry.ipdb/qqwry.ipdb" -o qqwry.ipdb

      - name: Generate geoip.dat file
        run: |
          node generate_geoip_dat.js qqwry.ipdb geoip.dat

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload geoip.dat to release
        uses: svenstaro/upload-release-action@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: geoip.dat
          asset_name: qqwry.dat
          tag: geoip-data
          overwrite: true
          body: "自动生成的qqwry数据库文件，基于纯真IP数据库。每日更新。"